template = "vue"
web_root = "dist/public"

[permissions]
paths = [
    { path = "*", type = "dir", mode = "750" },
    { path = "*", type = "file", mode = "640" },
    { path = "dist", type = "dir", mode = "755", recursive = true },
]

[shared]
paths = [
    { path = ".env", type = "file" },
    { path = "storage", type = "dir" },
]
