template = "rails"
web_root = "public"

[permissions]
paths = [
    { path = "*", type = "dir", mode = "750" },
    { path = "*", type = "file", mode = "640" },
    { path = "tmp", type = "dir", mode = "770", recursive = true },
    { path = "log", type = "dir", mode = "770", recursive = true },
    { path = "storage", type = "dir", mode = "770", recursive = true },
    { path = "public/assets", type = "dir", mode = "750", recursive = true },
]

[shared]
paths = [
    { path = ".env", type = "file" },
    { path = "storage", type = "dir" },
]
